/// <reference types="node" />

// Generated by scripts/gen-types.js - do not edit by hand.
// Run `npm run build:types` after changing src/constants.js.

import { Transform } from 'stream';

/** Anything the compression methods accept as input. */
export type InputType = string | Buffer | Uint8Array | DataView | ArrayBuffer;

/** Result shape returned when `info: true` is set. */
export interface InfoResult<T> {
  buffer: Buffer;
  engine: T;
}

export interface ZlibOptions {
  /** Flush behaviour during the stream - one of the Z_*_FLUSH constants. */
  flush?: number;
  /** Flush behaviour on the final chunk (default: Z_FINISH). */
  finishFlush?: number;
  /** Output chunk size in bytes (default: 16384, minimum 64). */
  chunkSize?: number;
  /** Window size, 9 to 15 (default: 15). InflateRaw also accepts 8. */
  windowBits?: number;
  /** Compression level, -1 to 9 (default: -1). */
  level?: number;
  /** Memory level, 1 to 9 (default: 8). */
  memLevel?: number;
  /** One of the Z_*_STRATEGY constants. */
  strategy?: number;
  /** Preset dictionary for deflate and inflate. */
  dictionary?: Buffer | Uint8Array | DataView | ArrayBuffer;
  /** Throws ERR_BUFFER_TOO_LARGE once output exceeds this many bytes. */
  maxOutputLength?: number;
  /** Return `{ buffer, engine }` instead of just the buffer. */
  info?: false;
}

export interface ZlibInfoOptions extends Omit<ZlibOptions, 'info'> {
  info: true;
}

export interface BrotliOptions {
  flush?: number;
  finishFlush?: number;
  chunkSize?: number;
  /** Keyed by the BROTLI_PARAM_* constants. */
  params?: Record<number, number>;
  maxOutputLength?: number;
  info?: false;
}

export interface BrotliInfoOptions extends Omit<BrotliOptions, 'info'> {
  info: true;
}

export interface ZstdOptions {
  flush?: number;
  finishFlush?: number;
  chunkSize?: number;
  /** Keyed by the ZSTD_c_* and ZSTD_d_* constants. */
  params?: Record<number, number>;
  maxOutputLength?: number;
  info?: false;
}

export interface ZstdInfoOptions extends Omit<ZstdOptions, 'info'> {
  info: true;
}

/** Base class shared by every codec in this package. */
export class ZlibBase extends Transform {
  /** Bytes handed to the engine, before compression or decompression. */
  readonly bytesWritten: number;
  /** Deprecated alias for bytesWritten, kept for parity with Node. */
  readonly bytesRead: number;
  readonly _closed: boolean;
  close(callback?: () => void): void;
  flush(kind?: number, callback?: () => void): void;
  flush(callback?: () => void): void;
  reset(): void;
  params(level: number, strategy: number, callback?: () => void): void;
}

export class Deflate extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class Inflate extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class DeflateRaw extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class InflateRaw extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class Gzip extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class Gunzip extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class Unzip extends ZlibBase {
  constructor(options?: ZlibOptions);
}

export class BrotliCompress extends ZlibBase {
  constructor(options?: BrotliOptions);
}

export class BrotliDecompress extends ZlibBase {
  constructor(options?: BrotliOptions);
}

/**
 * Present for API parity only. Constructing this throws
 * ERR_METHOD_NOT_IMPLEMENTED: there is no pure-JavaScript zstd encoder.
 */
export class ZstdCompress extends ZlibBase {
  constructor(options?: ZstdOptions);
}

export class ZstdDecompress extends ZlibBase {
  constructor(options?: ZstdOptions);
}

export function createDeflate(options?: ZlibOptions): Deflate;
export function createInflate(options?: ZlibOptions): Inflate;
export function createDeflateRaw(options?: ZlibOptions): DeflateRaw;
export function createInflateRaw(options?: ZlibOptions): InflateRaw;
export function createGzip(options?: ZlibOptions): Gzip;
export function createGunzip(options?: ZlibOptions): Gunzip;
export function createUnzip(options?: ZlibOptions): Unzip;
export function createBrotliCompress(options?: BrotliOptions): BrotliCompress;
export function createBrotliDecompress(options?: BrotliOptions): BrotliDecompress;
export function createZstdCompress(options?: ZstdOptions): ZstdCompress;
export function createZstdDecompress(options?: ZstdOptions): ZstdDecompress;

/**
 * deflate: returns a promise when no callback is supplied.
 */
export function deflate(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<Deflate>>;
export function deflate(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function deflate(buffer: InputType): Promise<Buffer>;
export function deflate(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<Deflate>) => void): void;
export function deflate(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function deflate(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function deflateSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<Deflate>;
export function deflateSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * inflate: returns a promise when no callback is supplied.
 */
export function inflate(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<Inflate>>;
export function inflate(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function inflate(buffer: InputType): Promise<Buffer>;
export function inflate(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<Inflate>) => void): void;
export function inflate(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function inflate(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function inflateSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<Inflate>;
export function inflateSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * deflateRaw: returns a promise when no callback is supplied.
 */
export function deflateRaw(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<DeflateRaw>>;
export function deflateRaw(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function deflateRaw(buffer: InputType): Promise<Buffer>;
export function deflateRaw(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<DeflateRaw>) => void): void;
export function deflateRaw(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function deflateRaw(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function deflateRawSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<DeflateRaw>;
export function deflateRawSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * inflateRaw: returns a promise when no callback is supplied.
 */
export function inflateRaw(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<InflateRaw>>;
export function inflateRaw(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function inflateRaw(buffer: InputType): Promise<Buffer>;
export function inflateRaw(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<InflateRaw>) => void): void;
export function inflateRaw(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function inflateRaw(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function inflateRawSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<InflateRaw>;
export function inflateRawSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * gzip: returns a promise when no callback is supplied.
 */
export function gzip(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<Gzip>>;
export function gzip(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function gzip(buffer: InputType): Promise<Buffer>;
export function gzip(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<Gzip>) => void): void;
export function gzip(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function gzip(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function gzipSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<Gzip>;
export function gzipSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * gunzip: returns a promise when no callback is supplied.
 */
export function gunzip(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<Gunzip>>;
export function gunzip(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function gunzip(buffer: InputType): Promise<Buffer>;
export function gunzip(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<Gunzip>) => void): void;
export function gunzip(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function gunzip(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function gunzipSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<Gunzip>;
export function gunzipSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * unzip: returns a promise when no callback is supplied.
 */
export function unzip(buffer: InputType, options: ZlibInfoOptions): Promise<InfoResult<Unzip>>;
export function unzip(buffer: InputType, options: ZlibOptions): Promise<Buffer>;
export function unzip(buffer: InputType): Promise<Buffer>;
export function unzip(buffer: InputType, options: ZlibInfoOptions, callback: (error: Error | null, result: InfoResult<Unzip>) => void): void;
export function unzip(buffer: InputType, options: ZlibOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function unzip(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function unzipSync(buffer: InputType, options: ZlibInfoOptions): InfoResult<Unzip>;
export function unzipSync(buffer: InputType, options?: ZlibOptions): Buffer;

/**
 * brotliCompress: returns a promise when no callback is supplied.
 */
export function brotliCompress(buffer: InputType, options: BrotliInfoOptions): Promise<InfoResult<BrotliCompress>>;
export function brotliCompress(buffer: InputType, options: BrotliOptions): Promise<Buffer>;
export function brotliCompress(buffer: InputType): Promise<Buffer>;
export function brotliCompress(buffer: InputType, options: BrotliInfoOptions, callback: (error: Error | null, result: InfoResult<BrotliCompress>) => void): void;
export function brotliCompress(buffer: InputType, options: BrotliOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function brotliCompress(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function brotliCompressSync(buffer: InputType, options: BrotliInfoOptions): InfoResult<BrotliCompress>;
export function brotliCompressSync(buffer: InputType, options?: BrotliOptions): Buffer;

/**
 * brotliDecompress: returns a promise when no callback is supplied.
 */
export function brotliDecompress(buffer: InputType, options: BrotliInfoOptions): Promise<InfoResult<BrotliDecompress>>;
export function brotliDecompress(buffer: InputType, options: BrotliOptions): Promise<Buffer>;
export function brotliDecompress(buffer: InputType): Promise<Buffer>;
export function brotliDecompress(buffer: InputType, options: BrotliInfoOptions, callback: (error: Error | null, result: InfoResult<BrotliDecompress>) => void): void;
export function brotliDecompress(buffer: InputType, options: BrotliOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function brotliDecompress(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function brotliDecompressSync(buffer: InputType, options: BrotliInfoOptions): InfoResult<BrotliDecompress>;
export function brotliDecompressSync(buffer: InputType, options?: BrotliOptions): Buffer;

/**
 * zstdCompress: returns a promise when no callback is supplied.
 *
 * @throws ERR_METHOD_NOT_IMPLEMENTED - zstd compression is not available
 * in a pure-JavaScript build. Decompression is supported.
 */
export function zstdCompress(buffer: InputType, options: ZstdInfoOptions): Promise<InfoResult<ZstdCompress>>;
export function zstdCompress(buffer: InputType, options: ZstdOptions): Promise<Buffer>;
export function zstdCompress(buffer: InputType): Promise<Buffer>;
export function zstdCompress(buffer: InputType, options: ZstdInfoOptions, callback: (error: Error | null, result: InfoResult<ZstdCompress>) => void): void;
export function zstdCompress(buffer: InputType, options: ZstdOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function zstdCompress(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function zstdCompressSync(buffer: InputType, options: ZstdInfoOptions): InfoResult<ZstdCompress>;
export function zstdCompressSync(buffer: InputType, options?: ZstdOptions): Buffer;

/**
 * zstdDecompress: returns a promise when no callback is supplied.
 */
export function zstdDecompress(buffer: InputType, options: ZstdInfoOptions): Promise<InfoResult<ZstdDecompress>>;
export function zstdDecompress(buffer: InputType, options: ZstdOptions): Promise<Buffer>;
export function zstdDecompress(buffer: InputType): Promise<Buffer>;
export function zstdDecompress(buffer: InputType, options: ZstdInfoOptions, callback: (error: Error | null, result: InfoResult<ZstdDecompress>) => void): void;
export function zstdDecompress(buffer: InputType, options: ZstdOptions, callback: (error: Error | null, result: Buffer) => void): void;
export function zstdDecompress(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;

export function zstdDecompressSync(buffer: InputType, options: ZstdInfoOptions): InfoResult<ZstdDecompress>;
export function zstdDecompressSync(buffer: InputType, options?: ZstdOptions): Buffer;

/** CRC-32 checksum (Node.js 22.2.0+). */
export function crc32(data: string | Buffer | Uint8Array | DataView, value?: number): number;

// Constants, generated from src/constants.js.
export const Z_NO_FLUSH: number;
export const Z_PARTIAL_FLUSH: number;
export const Z_SYNC_FLUSH: number;
export const Z_FULL_FLUSH: number;
export const Z_FINISH: number;
export const Z_BLOCK: number;
export const Z_TREES: number;
export const Z_OK: number;
export const Z_STREAM_END: number;
export const Z_NEED_DICT: number;
export const Z_ERRNO: number;
export const Z_STREAM_ERROR: number;
export const Z_DATA_ERROR: number;
export const Z_MEM_ERROR: number;
export const Z_BUF_ERROR: number;
export const Z_VERSION_ERROR: number;
export const Z_NO_COMPRESSION: number;
export const Z_BEST_SPEED: number;
export const Z_BEST_COMPRESSION: number;
export const Z_DEFAULT_COMPRESSION: number;
export const Z_FILTERED: number;
export const Z_HUFFMAN_ONLY: number;
export const Z_RLE: number;
export const Z_FIXED: number;
export const Z_DEFAULT_STRATEGY: number;
export const Z_BINARY: number;
export const Z_TEXT: number;
export const Z_UNKNOWN: number;
export const Z_DEFLATED: number;
export const Z_MIN_WINDOWBITS: number;
export const Z_MAX_WINDOWBITS: number;
export const Z_DEFAULT_WINDOWBITS: number;
export const Z_MIN_CHUNK: number;
export const Z_MAX_CHUNK: number;
export const Z_DEFAULT_CHUNK: number;
export const Z_MIN_MEMLEVEL: number;
export const Z_MAX_MEMLEVEL: number;
export const Z_DEFAULT_MEMLEVEL: number;
export const Z_MIN_LEVEL: number;
export const Z_MAX_LEVEL: number;
export const Z_DEFAULT_LEVEL: number;
export const ZLIB_VERNUM: number;
export const NONE: number;
export const DEFLATE: number;
export const INFLATE: number;
export const GZIP: number;
export const GUNZIP: number;
export const DEFLATERAW: number;
export const INFLATERAW: number;
export const UNZIP: number;
export const BROTLI_DECODE: number;
export const BROTLI_ENCODE: number;
export const ZSTD_COMPRESS: number;
export const ZSTD_DECOMPRESS: number;
export const BROTLI_OPERATION_PROCESS: number;
export const BROTLI_OPERATION_FLUSH: number;
export const BROTLI_OPERATION_FINISH: number;
export const BROTLI_OPERATION_EMIT_METADATA: number;
export const BROTLI_PARAM_MODE: number;
export const BROTLI_PARAM_QUALITY: number;
export const BROTLI_PARAM_LGWIN: number;
export const BROTLI_PARAM_LGBLOCK: number;
export const BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING: number;
export const BROTLI_PARAM_SIZE_HINT: number;
export const BROTLI_PARAM_LARGE_WINDOW: number;
export const BROTLI_PARAM_NPOSTFIX: number;
export const BROTLI_PARAM_NDIRECT: number;
export const BROTLI_MODE_GENERIC: number;
export const BROTLI_MODE_TEXT: number;
export const BROTLI_MODE_FONT: number;
export const BROTLI_DEFAULT_MODE: number;
export const BROTLI_MIN_QUALITY: number;
export const BROTLI_MAX_QUALITY: number;
export const BROTLI_DEFAULT_QUALITY: number;
export const BROTLI_MIN_WINDOW_BITS: number;
export const BROTLI_MAX_WINDOW_BITS: number;
export const BROTLI_LARGE_MAX_WINDOW_BITS: number;
export const BROTLI_DEFAULT_WINDOW: number;
export const BROTLI_MIN_INPUT_BLOCK_BITS: number;
export const BROTLI_MAX_INPUT_BLOCK_BITS: number;
export const BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION: number;
export const BROTLI_DECODER_PARAM_LARGE_WINDOW: number;
export const BROTLI_DECODER_RESULT_ERROR: number;
export const BROTLI_DECODER_RESULT_SUCCESS: number;
export const BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT: number;
export const BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT: number;
export const BROTLI_DECODER_NO_ERROR: number;
export const BROTLI_DECODER_SUCCESS: number;
export const BROTLI_DECODER_NEEDS_MORE_INPUT: number;
export const BROTLI_DECODER_NEEDS_MORE_OUTPUT: number;
export const BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE: number;
export const BROTLI_DECODER_ERROR_FORMAT_RESERVED: number;
export const BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE: number;
export const BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET: number;
export const BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME: number;
export const BROTLI_DECODER_ERROR_FORMAT_CL_SPACE: number;
export const BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE: number;
export const BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT: number;
export const BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1: number;
export const BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2: number;
export const BROTLI_DECODER_ERROR_FORMAT_TRANSFORM: number;
export const BROTLI_DECODER_ERROR_FORMAT_DICTIONARY: number;
export const BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS: number;
export const BROTLI_DECODER_ERROR_FORMAT_PADDING_1: number;
export const BROTLI_DECODER_ERROR_FORMAT_PADDING_2: number;
export const BROTLI_DECODER_ERROR_FORMAT_DISTANCE: number;
export const BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET: number;
export const BROTLI_DECODER_ERROR_INVALID_ARGUMENTS: number;
export const BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES: number;
export const BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS: number;
export const BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP: number;
export const BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1: number;
export const BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2: number;
export const BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES: number;
export const BROTLI_DECODER_ERROR_UNREACHABLE: number;
export const ZSTD_e_continue: number;
export const ZSTD_e_flush: number;
export const ZSTD_e_end: number;
export const ZSTD_c_compressionLevel: number;
export const ZSTD_c_windowLog: number;
export const ZSTD_c_hashLog: number;
export const ZSTD_c_chainLog: number;
export const ZSTD_c_searchLog: number;
export const ZSTD_c_minMatch: number;
export const ZSTD_c_targetLength: number;
export const ZSTD_c_strategy: number;
export const ZSTD_c_enableLongDistanceMatching: number;
export const ZSTD_c_ldmHashLog: number;
export const ZSTD_c_ldmMinMatch: number;
export const ZSTD_c_ldmBucketSizeLog: number;
export const ZSTD_c_ldmHashRateLog: number;
export const ZSTD_c_contentSizeFlag: number;
export const ZSTD_c_checksumFlag: number;
export const ZSTD_c_dictIDFlag: number;
export const ZSTD_c_nbWorkers: number;
export const ZSTD_c_jobSize: number;
export const ZSTD_c_overlapLog: number;
export const ZSTD_d_windowLogMax: number;
export const ZSTD_fast: number;
export const ZSTD_dfast: number;
export const ZSTD_greedy: number;
export const ZSTD_lazy: number;
export const ZSTD_lazy2: number;
export const ZSTD_btlazy2: number;
export const ZSTD_btopt: number;
export const ZSTD_btultra: number;
export const ZSTD_btultra2: number;
export const ZSTD_CLEVEL_DEFAULT: number;
export const ZSTD_error_no_error: number;
export const ZSTD_error_GENERIC: number;
export const ZSTD_error_prefix_unknown: number;
export const ZSTD_error_version_unsupported: number;
export const ZSTD_error_frameParameter_unsupported: number;
export const ZSTD_error_frameParameter_windowTooLarge: number;
export const ZSTD_error_corruption_detected: number;
export const ZSTD_error_checksum_wrong: number;
export const ZSTD_error_literals_headerWrong: number;
export const ZSTD_error_dictionary_corrupted: number;
export const ZSTD_error_dictionary_wrong: number;
export const ZSTD_error_dictionaryCreation_failed: number;
export const ZSTD_error_parameter_unsupported: number;
export const ZSTD_error_parameter_combination_unsupported: number;
export const ZSTD_error_parameter_outOfBound: number;
export const ZSTD_error_tableLog_tooLarge: number;
export const ZSTD_error_maxSymbolValue_tooLarge: number;
export const ZSTD_error_maxSymbolValue_tooSmall: number;
export const ZSTD_error_stabilityCondition_notRespected: number;
export const ZSTD_error_stage_wrong: number;
export const ZSTD_error_init_missing: number;
export const ZSTD_error_memory_allocation: number;
export const ZSTD_error_workSpace_tooSmall: number;
export const ZSTD_error_dstSize_tooSmall: number;
export const ZSTD_error_srcSize_wrong: number;
export const ZSTD_error_dstBuffer_null: number;
export const ZSTD_error_noForwardProgress_destFull: number;
export const ZSTD_error_noForwardProgress_inputEmpty: number;

export interface Constants {
  readonly Z_NO_FLUSH: number;
  readonly Z_PARTIAL_FLUSH: number;
  readonly Z_SYNC_FLUSH: number;
  readonly Z_FULL_FLUSH: number;
  readonly Z_FINISH: number;
  readonly Z_BLOCK: number;
  readonly Z_TREES: number;
  readonly Z_OK: number;
  readonly Z_STREAM_END: number;
  readonly Z_NEED_DICT: number;
  readonly Z_ERRNO: number;
  readonly Z_STREAM_ERROR: number;
  readonly Z_DATA_ERROR: number;
  readonly Z_MEM_ERROR: number;
  readonly Z_BUF_ERROR: number;
  readonly Z_VERSION_ERROR: number;
  readonly Z_NO_COMPRESSION: number;
  readonly Z_BEST_SPEED: number;
  readonly Z_BEST_COMPRESSION: number;
  readonly Z_DEFAULT_COMPRESSION: number;
  readonly Z_FILTERED: number;
  readonly Z_HUFFMAN_ONLY: number;
  readonly Z_RLE: number;
  readonly Z_FIXED: number;
  readonly Z_DEFAULT_STRATEGY: number;
  readonly Z_BINARY: number;
  readonly Z_TEXT: number;
  readonly Z_UNKNOWN: number;
  readonly Z_DEFLATED: number;
  readonly Z_MIN_WINDOWBITS: number;
  readonly Z_MAX_WINDOWBITS: number;
  readonly Z_DEFAULT_WINDOWBITS: number;
  readonly Z_MIN_CHUNK: number;
  readonly Z_MAX_CHUNK: number;
  readonly Z_DEFAULT_CHUNK: number;
  readonly Z_MIN_MEMLEVEL: number;
  readonly Z_MAX_MEMLEVEL: number;
  readonly Z_DEFAULT_MEMLEVEL: number;
  readonly Z_MIN_LEVEL: number;
  readonly Z_MAX_LEVEL: number;
  readonly Z_DEFAULT_LEVEL: number;
  readonly ZLIB_VERNUM: number;
  readonly NONE: number;
  readonly DEFLATE: number;
  readonly INFLATE: number;
  readonly GZIP: number;
  readonly GUNZIP: number;
  readonly DEFLATERAW: number;
  readonly INFLATERAW: number;
  readonly UNZIP: number;
  readonly BROTLI_DECODE: number;
  readonly BROTLI_ENCODE: number;
  readonly ZSTD_COMPRESS: number;
  readonly ZSTD_DECOMPRESS: number;
  readonly BROTLI_OPERATION_PROCESS: number;
  readonly BROTLI_OPERATION_FLUSH: number;
  readonly BROTLI_OPERATION_FINISH: number;
  readonly BROTLI_OPERATION_EMIT_METADATA: number;
  readonly BROTLI_PARAM_MODE: number;
  readonly BROTLI_PARAM_QUALITY: number;
  readonly BROTLI_PARAM_LGWIN: number;
  readonly BROTLI_PARAM_LGBLOCK: number;
  readonly BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING: number;
  readonly BROTLI_PARAM_SIZE_HINT: number;
  readonly BROTLI_PARAM_LARGE_WINDOW: number;
  readonly BROTLI_PARAM_NPOSTFIX: number;
  readonly BROTLI_PARAM_NDIRECT: number;
  readonly BROTLI_MODE_GENERIC: number;
  readonly BROTLI_MODE_TEXT: number;
  readonly BROTLI_MODE_FONT: number;
  readonly BROTLI_DEFAULT_MODE: number;
  readonly BROTLI_MIN_QUALITY: number;
  readonly BROTLI_MAX_QUALITY: number;
  readonly BROTLI_DEFAULT_QUALITY: number;
  readonly BROTLI_MIN_WINDOW_BITS: number;
  readonly BROTLI_MAX_WINDOW_BITS: number;
  readonly BROTLI_LARGE_MAX_WINDOW_BITS: number;
  readonly BROTLI_DEFAULT_WINDOW: number;
  readonly BROTLI_MIN_INPUT_BLOCK_BITS: number;
  readonly BROTLI_MAX_INPUT_BLOCK_BITS: number;
  readonly BROTLI_DECODER_PARAM_DISABLE_RING_BUFFER_REALLOCATION: number;
  readonly BROTLI_DECODER_PARAM_LARGE_WINDOW: number;
  readonly BROTLI_DECODER_RESULT_ERROR: number;
  readonly BROTLI_DECODER_RESULT_SUCCESS: number;
  readonly BROTLI_DECODER_RESULT_NEEDS_MORE_INPUT: number;
  readonly BROTLI_DECODER_RESULT_NEEDS_MORE_OUTPUT: number;
  readonly BROTLI_DECODER_NO_ERROR: number;
  readonly BROTLI_DECODER_SUCCESS: number;
  readonly BROTLI_DECODER_NEEDS_MORE_INPUT: number;
  readonly BROTLI_DECODER_NEEDS_MORE_OUTPUT: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_NIBBLE: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_RESERVED: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_EXUBERANT_META_NIBBLE: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_ALPHABET: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_SIMPLE_HUFFMAN_SAME: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_CL_SPACE: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_HUFFMAN_SPACE: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_CONTEXT_MAP_REPEAT: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_1: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_BLOCK_LENGTH_2: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_TRANSFORM: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_DICTIONARY: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_WINDOW_BITS: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_PADDING_1: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_PADDING_2: number;
  readonly BROTLI_DECODER_ERROR_FORMAT_DISTANCE: number;
  readonly BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET: number;
  readonly BROTLI_DECODER_ERROR_INVALID_ARGUMENTS: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MODES: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_TREE_GROUPS: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_CONTEXT_MAP: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_1: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_RING_BUFFER_2: number;
  readonly BROTLI_DECODER_ERROR_ALLOC_BLOCK_TYPE_TREES: number;
  readonly BROTLI_DECODER_ERROR_UNREACHABLE: number;
  readonly ZSTD_e_continue: number;
  readonly ZSTD_e_flush: number;
  readonly ZSTD_e_end: number;
  readonly ZSTD_c_compressionLevel: number;
  readonly ZSTD_c_windowLog: number;
  readonly ZSTD_c_hashLog: number;
  readonly ZSTD_c_chainLog: number;
  readonly ZSTD_c_searchLog: number;
  readonly ZSTD_c_minMatch: number;
  readonly ZSTD_c_targetLength: number;
  readonly ZSTD_c_strategy: number;
  readonly ZSTD_c_enableLongDistanceMatching: number;
  readonly ZSTD_c_ldmHashLog: number;
  readonly ZSTD_c_ldmMinMatch: number;
  readonly ZSTD_c_ldmBucketSizeLog: number;
  readonly ZSTD_c_ldmHashRateLog: number;
  readonly ZSTD_c_contentSizeFlag: number;
  readonly ZSTD_c_checksumFlag: number;
  readonly ZSTD_c_dictIDFlag: number;
  readonly ZSTD_c_nbWorkers: number;
  readonly ZSTD_c_jobSize: number;
  readonly ZSTD_c_overlapLog: number;
  readonly ZSTD_d_windowLogMax: number;
  readonly ZSTD_fast: number;
  readonly ZSTD_dfast: number;
  readonly ZSTD_greedy: number;
  readonly ZSTD_lazy: number;
  readonly ZSTD_lazy2: number;
  readonly ZSTD_btlazy2: number;
  readonly ZSTD_btopt: number;
  readonly ZSTD_btultra: number;
  readonly ZSTD_btultra2: number;
  readonly ZSTD_CLEVEL_DEFAULT: number;
  readonly ZSTD_error_no_error: number;
  readonly ZSTD_error_GENERIC: number;
  readonly ZSTD_error_prefix_unknown: number;
  readonly ZSTD_error_version_unsupported: number;
  readonly ZSTD_error_frameParameter_unsupported: number;
  readonly ZSTD_error_frameParameter_windowTooLarge: number;
  readonly ZSTD_error_corruption_detected: number;
  readonly ZSTD_error_checksum_wrong: number;
  readonly ZSTD_error_literals_headerWrong: number;
  readonly ZSTD_error_dictionary_corrupted: number;
  readonly ZSTD_error_dictionary_wrong: number;
  readonly ZSTD_error_dictionaryCreation_failed: number;
  readonly ZSTD_error_parameter_unsupported: number;
  readonly ZSTD_error_parameter_combination_unsupported: number;
  readonly ZSTD_error_parameter_outOfBound: number;
  readonly ZSTD_error_tableLog_tooLarge: number;
  readonly ZSTD_error_maxSymbolValue_tooLarge: number;
  readonly ZSTD_error_maxSymbolValue_tooSmall: number;
  readonly ZSTD_error_stabilityCondition_notRespected: number;
  readonly ZSTD_error_stage_wrong: number;
  readonly ZSTD_error_init_missing: number;
  readonly ZSTD_error_memory_allocation: number;
  readonly ZSTD_error_workSpace_tooSmall: number;
  readonly ZSTD_error_dstSize_tooSmall: number;
  readonly ZSTD_error_srcSize_wrong: number;
  readonly ZSTD_error_dstBuffer_null: number;
  readonly ZSTD_error_noForwardProgress_destFull: number;
  readonly ZSTD_error_noForwardProgress_inputEmpty: number;
}

export const constants: Constants;

/** Return code names, mapped in both directions. */
export const codes: Readonly<Record<string, string | number>>;
