'use strict';

// Emits index.d.ts. The constant declarations are generated from
// src/constants.js so the two can never drift apart.
var constants = require('../src/constants');

var CONSTANT_NAMES = Object.keys(constants);

// name, stream class, options interface, and whether the method exists only
// to preserve API surface (zstd compression has no pure-JS implementation).
var ASYNC_METHODS = [
  ['deflate', 'Deflate', 'Zlib'],
  ['inflate', 'Inflate', 'Zlib'],
  ['deflateRaw', 'DeflateRaw', 'Zlib'],
  ['inflateRaw', 'InflateRaw', 'Zlib'],
  ['gzip', 'Gzip', 'Zlib'],
  ['gunzip', 'Gunzip', 'Zlib'],
  ['unzip', 'Unzip', 'Zlib'],
  ['brotliCompress', 'BrotliCompress', 'Brotli'],
  ['brotliDecompress', 'BrotliDecompress', 'Brotli'],
  ['zstdCompress', 'ZstdCompress', 'Zstd'],
  ['zstdDecompress', 'ZstdDecompress', 'Zstd']
];

var UNSUPPORTED = { zstdCompress: true };

var out = [];
function w(line) { out.push(line === undefined ? '' : line); }

w('/// <reference types="node" />');
w();
w('// Generated by scripts/gen-types.js - do not edit by hand.');
w('// Run `npm run build:types` after changing src/constants.js.');
w();
w("import { Transform } from 'stream';");
w();
w('/** Anything the compression methods accept as input. */');
w('export type InputType = string | Buffer | Uint8Array | DataView | ArrayBuffer;');
w();
w('/** Result shape returned when `info: true` is set. */');
w('export interface InfoResult<T> {');
w('  buffer: Buffer;');
w('  engine: T;');
w('}');
w();
w('export interface ZlibOptions {');
w('  /** Flush behaviour during the stream - one of the Z_*_FLUSH constants. */');
w('  flush?: number;');
w('  /** Flush behaviour on the final chunk (default: Z_FINISH). */');
w('  finishFlush?: number;');
w('  /** Output chunk size in bytes (default: 16384, minimum 64). */');
w('  chunkSize?: number;');
w('  /** Window size, 9 to 15 (default: 15). InflateRaw also accepts 8. */');
w('  windowBits?: number;');
w('  /** Compression level, -1 to 9 (default: -1). */');
w('  level?: number;');
w('  /** Memory level, 1 to 9 (default: 8). */');
w('  memLevel?: number;');
w('  /** One of the Z_*_STRATEGY constants. */');
w('  strategy?: number;');
w('  /** Preset dictionary for deflate and inflate. */');
w('  dictionary?: Buffer | Uint8Array | DataView | ArrayBuffer;');
w('  /** Throws ERR_BUFFER_TOO_LARGE once output exceeds this many bytes. */');
w('  maxOutputLength?: number;');
w('  /** Return `{ buffer, engine }` instead of just the buffer. */');
w('  info?: false;');
w('}');
w();
w('export interface ZlibInfoOptions extends Omit<ZlibOptions, \'info\'> {');
w('  info: true;');
w('}');
w();
w('export interface BrotliOptions {');
w('  flush?: number;');
w('  finishFlush?: number;');
w('  chunkSize?: number;');
w('  /** Keyed by the BROTLI_PARAM_* constants. */');
w('  params?: Record<number, number>;');
w('  maxOutputLength?: number;');
w('  info?: false;');
w('}');
w();
w('export interface BrotliInfoOptions extends Omit<BrotliOptions, \'info\'> {');
w('  info: true;');
w('}');
w();
w('export interface ZstdOptions {');
w('  flush?: number;');
w('  finishFlush?: number;');
w('  chunkSize?: number;');
w('  /** Keyed by the ZSTD_c_* and ZSTD_d_* constants. */');
w('  params?: Record<number, number>;');
w('  maxOutputLength?: number;');
w('  info?: false;');
w('}');
w();
w('export interface ZstdInfoOptions extends Omit<ZstdOptions, \'info\'> {');
w('  info: true;');
w('}');
w();
w('/** Base class shared by every codec in this package. */');
w('export class ZlibBase extends Transform {');
w('  /** Bytes handed to the engine, before compression or decompression. */');
w('  readonly bytesWritten: number;');
w('  /** Deprecated alias for bytesWritten, kept for parity with Node. */');
w('  readonly bytesRead: number;');
w('  readonly _closed: boolean;');
w('  close(callback?: () => void): void;');
w('  flush(kind?: number, callback?: () => void): void;');
w('  flush(callback?: () => void): void;');
w('  reset(): void;');
w('  params(level: number, strategy: number, callback?: () => void): void;');
w('}');
w();

['Deflate', 'Inflate', 'DeflateRaw', 'InflateRaw', 'Gzip', 'Gunzip', 'Unzip'].forEach(function (name) {
  w('export class ' + name + ' extends ZlibBase {');
  w('  constructor(options?: ZlibOptions);');
  w('}');
  w();
});

['BrotliCompress', 'BrotliDecompress'].forEach(function (name) {
  w('export class ' + name + ' extends ZlibBase {');
  w('  constructor(options?: BrotliOptions);');
  w('}');
  w();
});

w('/**');
w(' * Present for API parity only. Constructing this throws');
w(' * ERR_METHOD_NOT_IMPLEMENTED: there is no pure-JavaScript zstd encoder.');
w(' */');
w('export class ZstdCompress extends ZlibBase {');
w('  constructor(options?: ZstdOptions);');
w('}');
w();
w('export class ZstdDecompress extends ZlibBase {');
w('  constructor(options?: ZstdOptions);');
w('}');
w();

var FACTORIES = [
  ['createDeflate', 'Deflate', 'ZlibOptions'],
  ['createInflate', 'Inflate', 'ZlibOptions'],
  ['createDeflateRaw', 'DeflateRaw', 'ZlibOptions'],
  ['createInflateRaw', 'InflateRaw', 'ZlibOptions'],
  ['createGzip', 'Gzip', 'ZlibOptions'],
  ['createGunzip', 'Gunzip', 'ZlibOptions'],
  ['createUnzip', 'Unzip', 'ZlibOptions'],
  ['createBrotliCompress', 'BrotliCompress', 'BrotliOptions'],
  ['createBrotliDecompress', 'BrotliDecompress', 'BrotliOptions'],
  ['createZstdCompress', 'ZstdCompress', 'ZstdOptions'],
  ['createZstdDecompress', 'ZstdDecompress', 'ZstdOptions']
];

FACTORIES.forEach(function (f) {
  w('export function ' + f[0] + '(options?: ' + f[2] + '): ' + f[1] + ';');
});
w();

ASYNC_METHODS.forEach(function (m) {
  var name = m[0];
  var cls = m[1];
  var opts = m[2] + 'Options';
  var infoOpts = m[2] + 'InfoOptions';

  w('/**');
  w(' * ' + name + ': returns a promise when no callback is supplied.');
  if (UNSUPPORTED[name]) {
    w(' *');
    w(' * @throws ERR_METHOD_NOT_IMPLEMENTED - zstd compression is not available');
    w(' * in a pure-JavaScript build. Decompression is supported.');
  }
  w(' */');
  w('export function ' + name + '(buffer: InputType, options: ' + infoOpts + '): Promise<InfoResult<' + cls + '>>;');
  w('export function ' + name + '(buffer: InputType, options: ' + opts + '): Promise<Buffer>;');
  w('export function ' + name + '(buffer: InputType): Promise<Buffer>;');
  w('export function ' + name + '(buffer: InputType, options: ' + infoOpts + ', callback: (error: Error | null, result: InfoResult<' + cls + '>) => void): void;');
  w('export function ' + name + '(buffer: InputType, options: ' + opts + ', callback: (error: Error | null, result: Buffer) => void): void;');
  w('export function ' + name + '(buffer: InputType, callback: (error: Error | null, result: Buffer) => void): void;');
  w();
  w('export function ' + name + 'Sync(buffer: InputType, options: ' + infoOpts + '): InfoResult<' + cls + '>;');
  w('export function ' + name + 'Sync(buffer: InputType, options?: ' + opts + '): Buffer;');
  w();
});

w('/** CRC-32 checksum (Node.js 22.2.0+). */');
w('export function crc32(data: string | Buffer | Uint8Array | DataView, value?: number): number;');
w();

w('// Constants, generated from src/constants.js.');
CONSTANT_NAMES.forEach(function (name) {
  w('export const ' + name + ': number;');
});
w();

w('export interface Constants {');
CONSTANT_NAMES.forEach(function (name) {
  w('  readonly ' + name + ': number;');
});
w('}');
w();
w('export const constants: Constants;');
w();
w('/** Return code names, mapped in both directions. */');
w('export const codes: Readonly<Record<string, string | number>>;');

process.stdout.write(out.join('\n') + '\n');
process.stderr.write('generated ' + CONSTANT_NAMES.length + ' constants, ' +
  ASYNC_METHODS.length + ' method pairs\n');
